### ISSUE TITLE
Updated to new pylexibank

### ISSUE THREAD

**Issue by chrzyki** [lexibank/logos#1]
https://github.com/lexibank/logos/commit/d7e9038e92b8257c300799c7de8c892258ba752b

Also updated IDs. Please note this issue:

https://github.com/lexibank/logos/blob/d7e9038e92b8257c300799c7de8c892258ba752b/lexibank_logos.py#L17

I couldn't find a way (without changes to the core libraries) to pass `_check_id=False` to the sources to allow the bib key for `CLICS-1.0.0`.

**Comment by LinguList** [comment]
Nice. For Evobib, the new keys are important, as they allow for a consistent storing of Software across versions, with varying authors. The most recent version is, similare to latestdoi n zenodo, always the name of the software without versioning. I could switch to underscores, but bibtex keys in latex allow this treatment. One might tweak evobib in such a way that it returns another bibtex-key on demand.

**Comment by LinguList** [comment]
The question about evobipping these sources is also a general question. It has the advantage that updates will get included immediately.

See Ian's (Joo Ian) paper for which Kristina added the conceptlist yesterday: the paper is available ahead of print. This means, in half a  year, we have to update it. If IDs stay consistent, this means that the updates are simplified.

The alternative is: just place the evobib in sources.bib, and never call the download function, and manually adjust it, as we also do in many datasets. 

We need a discussion (maybe a thread/issue on pylexibank) of how to handle this, as bibtex-adding is one of the things that annoy me when adding datasets.

But the easiest way would be: use "evobibasbibtex" only if there's no "sources.bib", and if it's there, leave the sources.bib in raw, and have them for manipulating the bibtex, in case this is needed.

Similar to what I do now: I use iso2glottocode once, but then I add the language file in `etc/languages.csv` along with geo-coordinates from glottolog, as this makes the installation run faster...

**Comment by SimonGreenhill** [comment]
Yeah, I like the idea of just including the sources.bib file directly in lexibank, as this makes it more selfcontained and source information is *fundmental*. 

Also note that getEvobibAsBibtex happily returns this if it can't find the reference, so we need to visually inspect the sources.bib anyway:

```bibtex
@misc{Zgraggen1980NA,
Note={missing source}

}
```

(the Madang dataset for example has been showing source=100% although it's actually 0 :) )

**Comment by chrzyki** [comment]
Oki, will change this!

On 29 Oct 2019 11:38, Simon J Greenhill <notifications@github.com> wrote:

Yeah, I like the idea of just including the sources.bib file directly in lexibank, as this makes it more selfcontained and source information is fundmental.

Also note that getEvobibAsBibtex happily returns this if it can't find the reference, so we need to visually inspect the sources.bib anyway:

@misc{Zgraggen1980NA,
Note={missing source}

}

(the Madang dataset for example has been showing source=100% although it's actually 0 :) )

**Comment by chrzyki** [comment]
Done in https://github.com/lexibank/logos/commit/1a65b8d7ce8eb04179d033df6f9351f2c0b4345e.
