### ISSUE TITLE
CONTRIBUTORS.md?

### ISSUE THREAD

**Issue by johenglisch** [lexibank/logos#2]
Currently the `CONTRIBUTORS.md` says `Logos group`.  Should it include the people from the original clics data instead?

> List, Johann-Mattis, Thomas Mayer, Anselm Terhalle, and Matthias Urban

 (and put the `Logos group` into the curators/data rearrangers/etc. category)

**Comment by LinguList** [comment]
In fact, it was myself who accumulated all data, the others did not 
actively take part in this, so it can in my opinion be attributed to me, 
as the person which extracted parts of the data provided by logos.

**Comment by johenglisch** [comment]
Like that?

**Comment by LinguList** [comment]
Yes!
